/*
SQLyog Ultimate v13.1.1 (64 bit)
MySQL - 10.4.21-MariaDB : Database - sunshine
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`sunshine` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `sunshine`;

/*Table structure for table `contactus` */

DROP TABLE IF EXISTS `contactus`;

CREATE TABLE `contactus` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `message` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `contactus` */

/*Table structure for table `failed_jobs` */

DROP TABLE IF EXISTS `failed_jobs`;

CREATE TABLE `failed_jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `failed_jobs` */

/*Table structure for table `gallery` */

DROP TABLE IF EXISTS `gallery`;

CREATE TABLE `gallery` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `gallery` */

insert  into `gallery`(`id`,`title`,`image`,`slug`,`description`,`created_at`,`updated_at`,`deleted_at`) values 
(1,'nisi quia sint ex necessitatibus similique','1654083931.png','laboriosam-recusandae-esse','Aperiam rerum rerum quasi sint. Ducimus itaque soluta praesentium quia fugiat voluptas non aut. Et ut id eaque aut. Sit neque harum quibusdam ratione. Dolorem recusandae alias a minus sit ipsum autem. Ad adipisci asperiores fuga quaerat inventore quis nulla. Cupiditate fugit reprehenderit unde rerum. Facilis non non assumenda occaecati aut sunt deleniti. Alias sunt quam autem earum alias. Voluptatem eaque illo sed dolor. Repellendus quidem harum maiores dolor. Recusandae cupiditate rerum et ea sequi sit sit ipsa. Architecto at quod aspernatur distinctio dicta explicabo. Dolor atque soluta amet qui sapiente ut velit. Nobis et voluptas ut eum assumenda culpa. Ducimus quis ea nihil eos architecto. Inventore sit numquam et hic similique soluta et. Sapiente et excepturi cumque ipsum nostrum laborum eveniet. Ut qui vel rerum eum. Sint a pariatur suscipit doloribus ad et. Impedit molestiae quibusdam dicta est. Temporibus nostrum nisi fuga libero. Tenetur numquam distinctio perspiciatis et quis suscipit repellat. Deleniti soluta quod deleniti ut. Qui ut fugit officiis at animi eveniet. Libero eum quis minima et dolore non maiores. Id adipisci eaque accusantium et. Asperiores repudiandae possimus voluptatem deleniti necessitatibus esse omnis. Quis beatae sequi odio reiciendis. Qui recusandae laudantium non consequatur quia. Ipsam reiciendis praesentium enim enim quia fugit quasi. Illum magni rerum possimus neque qui quae aut. Possimus et dignissimos illum error quis iusto eveniet. Quas sunt et velit non ratione necessitatibus tempora quisquam. Vel dolorum adipisci magnam quo laborum ea sunt. Praesentium doloremque dicta saepe et ut. Et saepe quidem architecto quis enim. Omnis minima rerum et vel. Et necessitatibus quis et adipisci et. Sapiente nobis sit maxime ducimus qui est.','2022-06-01 11:32:48','2022-06-01 11:45:31',NULL),
(2,'alias voluptas nulla voluptas sit quae','1654083931.png','animi-totam-atque','Voluptatem porro doloribus est vel sit. At itaque quam magnam praesentium. Voluptas voluptatem cupiditate et ut voluptas qui tempore. Consequatur et est maiores earum nihil. Ut quasi explicabo possimus id sequi minima a. Et consequuntur modi nemo ea quibusdam. Voluptatem magni commodi dolore incidunt consequuntur quia. Consequatur nostrum aperiam dolore itaque iste perspiciatis qui. Est labore quas aut perferendis sint velit. Aliquid ipsam occaecati possimus perferendis id a alias. Non numquam reiciendis rerum illo. In qui veniam odit quis. Alias doloribus commodi tenetur in ut necessitatibus nihil. Nihil est dolor hic ipsam. Quasi a possimus dolorum consequuntur. Officia et sed non hic. Sed fuga et omnis odio corrupti. Vel voluptatem totam at voluptatum vel non. Iure aut dolore dicta delectus delectus quo. Natus nihil deserunt perspiciatis voluptatem accusantium. Aut mollitia velit laboriosam reiciendis commodi eos quisquam. Cupiditate rerum quia ut quis inventore necessitatibus perferendis. Repudiandae aut pariatur ducimus officia. Nihil molestiae aspernatur similique quos excepturi. Ullam minus rem ipsam cupiditate aut quidem id velit. Id ab corporis sed consequuntur et nemo enim. Praesentium nihil aut voluptatem. Consequatur sunt corporis ipsam cupiditate nesciunt. At et molestiae sed dicta. Tenetur iure rerum ducimus et. Eligendi vero voluptatem modi nihil nostrum et. Maiores amet numquam officia nihil vitae. Quo rem quis corrupti quo rem error non. Eligendi totam quaerat eos et unde id ullam quia. Animi et voluptatem accusantium ab ut vitae. Corrupti enim recusandae esse inventore. Accusamus voluptas quidem a aliquam molestiae voluptatibus. Dolor est reiciendis nemo sapiente dolores. Voluptatibus ea odio et et quos impedit aut velit. Dolores accusamus officia in reprehenderit perferendis id.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(3,'Hill','1654083931.png','non-non-delectus','Rerum impedit amet consequatur omnis aspernatur. Vel voluptate est asperiores ullam ut et. Tempore harum qui est dolorem cupiditate cupiditate voluptates. Dolor sint labore et vitae. Ducimus enim saepe nisi. Similique explicabo in aut alias. Dolorem ut ducimus assumenda nemo. Excepturi ratione eum et nemo. Est qui voluptas sit. Id non natus tempora natus ut labore. Culpa eos ipsum voluptatem neque molestias. Dolores impedit id nihil molestiae. Cupiditate reiciendis alias ipsa pariatur modi. Consequatur architecto voluptas dolor ex facere ad dicta. Corporis quos consectetur a laudantium ab. Quibusdam vero consequuntur voluptatem sit deserunt et laboriosam. Neque et quasi labore reiciendis molestiae. Quos perferendis ut voluptatibus officiis molestias et. Eum eveniet quaerat animi ea. Sunt in culpa ea velit quis sunt minus. Dolorem dolorem sed molestiae sequi omnis enim dignissimos sint. Sit quaerat tenetur pariatur aut assumenda cupiditate. Qui labore qui non autem et. Sit officiis beatae sunt laboriosam voluptatum et nostrum. Incidunt pariatur tenetur accusantium fugit dolorem officia. Facere explicabo maxime eos magnam praesentium. Vero praesentium ab dolores dolores laborum. Facere sunt expedita impedit vero laboriosam. Et autem vero quae ad. Eaque deserunt quos consequatur qui enim sit. Quod eligendi temporibus dolores debitis omnis. Laudantium a natus earum voluptate eligendi deleniti dolorem earum. Id atque ut cupiditate iste. Consequuntur dicta enim omnis optio asperiores tenetur veniam. Repellat laborum ut vitae dolorem placeat velit. Quasi consectetur sint quis quibusdam et et consequatur. Corrupti placeat blanditiis dolor natus. Est ducimus magnam commodi eum cumque. Sit recusandae consequatur eveniet assumenda. Magni velit cupiditate eos amet quasi atque.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(4,'eos laboriosam ut sint sequi natus','1654083931.png','illum-similique-et','Amet illo illum maxime dolor dolorem quia. Nostrum aut illo ipsa facere. Inventore tempora voluptatem qui dicta. Optio molestiae assumenda et quos at. Beatae sunt accusamus amet quisquam sint tenetur. Maxime et consectetur inventore et voluptatem. Voluptatum assumenda tempore qui itaque non amet dolorem. Quidem perferendis quibusdam dolor deserunt earum et. Dolorem reprehenderit molestias voluptate. Nam dolorem quasi nam necessitatibus. Facere accusantium saepe consequuntur. Exercitationem repellat voluptatem quas itaque excepturi ullam quas. Est eum modi eos accusamus. Laudantium voluptates expedita fuga corporis voluptatem iste. Eaque ducimus reprehenderit beatae vel sint. Eveniet exercitationem debitis blanditiis pariatur aliquid. Eos provident architecto aut ipsam culpa. Rem unde sed possimus omnis adipisci tenetur quod. Sed est quaerat qui ut ab doloremque qui iusto. Exercitationem porro est aut error dicta molestiae. Nihil autem possimus vel harum. Aut in quam sunt voluptatibus. Maxime voluptas consequatur sequi consequatur est impedit facere aliquam. Adipisci porro quis repellat ab. In voluptatem sed non ipsum voluptatem ipsam qui. Non voluptate est cum iusto. Distinctio ea eius qui aut. Quos debitis perspiciatis ut sit voluptatem veniam error. Occaecati ad laborum temporibus. Autem a occaecati quae totam et. Ut eius dolores aut occaecati. Laudantium reprehenderit ut quis itaque fugiat. Qui qui error velit consequuntur rerum. Inventore qui aut velit et odio mollitia ab. Sunt ipsam quia debitis. Est ullam debitis et quae qui repellat. Vel adipisci beatae hic corporis. Optio quo sit optio eum. Distinctio temporibus tempora dolorum eveniet harum. Earum recusandae incidunt ipsum placeat hic.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(5,'nam atque quia aut et voluptatem','1654083931.png','explicabo-maiores-cupiditate','Nihil animi dolorem sed quibusdam sunt. Cum totam et dignissimos ut voluptatibus dolore temporibus. Sit rem sed magni ut tempore ut tenetur. Quia et qui quam repudiandae dolorem fugiat dolore. Odio earum soluta mollitia nam repudiandae. Rem quidem dicta nam facere blanditiis sed. Blanditiis id optio explicabo dolores. Nihil consequuntur aut dicta architecto aut ducimus nemo est. Illo unde earum officia consequatur architecto. Est omnis cumque aut quibusdam minima fugit. Est nemo minus molestias sint a asperiores molestiae. Incidunt ut non repudiandae voluptatem in omnis. Aspernatur quaerat voluptatem optio mollitia nisi quas modi. Quos quo expedita incidunt ipsa. Necessitatibus consequatur laudantium distinctio. Qui praesentium rerum commodi voluptatem et saepe. Sit aut hic blanditiis dolorem consequatur maiores. Soluta ut non ut qui id quidem eligendi. Et aspernatur ratione quia. Rerum voluptatum molestiae pariatur culpa et in fugit. Impedit ipsum vel sit corporis fuga. Nulla tempora consequatur accusantium iste. Laudantium qui ut aut voluptatem est. Nihil molestiae sit ipsa et a illo aut. Eum consectetur corporis tempora expedita. Quos nobis rerum tempore nulla laudantium. Soluta quasi et enim ullam in quod soluta. Soluta voluptas magnam nostrum doloremque beatae consequatur. Minima illo maxime fuga qui officia. Fugiat itaque vel nisi ut et sint. Sit culpa omnis soluta et unde ipsam. Dolor dolorum sit est nemo atque cupiditate. Maxime recusandae in et ut quis. Tenetur optio delectus eligendi consequatur sunt. Velit dolores dolor maxime numquam in ea dolorem. Eos ut aut magnam quae fuga. Corrupti vero quisquam ipsum. Voluptates cumque necessitatibus natus. Aliquam illo asperiores provident distinctio consequatur perspiciatis iure culpa. Quae id consequatur repellat commodi quia illo.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(6,'corrupti adipisci hic aliquam aut blanditiis','1654083931.png','consequatur-deserunt-quo','Velit aut id et in officiis. Exercitationem fugiat eligendi quam quia deserunt. Dolor earum alias velit voluptas ipsam. Dolorum distinctio iusto deleniti fugiat temporibus doloremque accusantium. Commodi omnis repudiandae asperiores corporis. Vero ratione dolorum nisi odit possimus et tempora. Aliquid eos ad occaecati maxime. Commodi delectus iste doloremque exercitationem animi qui perferendis natus. Similique eos nam nam placeat beatae magni vel. Ratione facilis quod perspiciatis exercitationem officia et magnam. Itaque ullam sed qui deserunt. Ut commodi voluptatem atque illum voluptas aut. Excepturi quidem incidunt dolores. Ut et tenetur suscipit optio in. Sed autem molestias atque provident cupiditate est rem. Quaerat totam expedita aut atque eum molestiae possimus voluptatibus. Quibusdam deserunt ut quo occaecati dignissimos. Quisquam expedita expedita et doloremque sit. Libero voluptatem ratione libero et qui consequuntur aut architecto. Porro ut fugit vel numquam velit eligendi eligendi eligendi. Nulla vitae ipsa eos doloribus ut. Aspernatur id impedit quisquam itaque numquam. Fugit incidunt aliquid aliquam molestias. Minus optio est laborum vero esse soluta commodi eum. Sequi aut in et adipisci dolor a et voluptas. Molestias odit voluptatem harum omnis blanditiis. Et voluptatibus eum earum iusto quos. Illum voluptate alias ut. Dolore similique quo ex laboriosam. Qui aut illum vel ea rerum. Fuga deserunt sit impedit consequatur perferendis autem alias. Et nam numquam qui ex et dolorem nisi. Aut architecto sunt consequuntur rerum sit. Itaque quae qui molestiae officia vel in ex. Debitis molestiae ipsum nobis omnis excepturi saepe enim. Et recusandae ut eum in magni. Voluptatibus qui aliquam quia aspernatur quam sequi sed. Aliquam ad rerum ea nesciunt in aut. Beatae porro vero sunt. Minima amet perferendis eius aut ut quasi velit.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(7,'delectus delectus ab enim commodi laudantium','1654083931.png','ex-minima-et','Reiciendis alias eum ad eum ad quia. Nobis reiciendis pariatur consequatur numquam voluptatum. Qui reprehenderit sint quasi. Est atque unde aut in iure. Dolor ut repellendus et et. Tempora quia nostrum hic dicta minus dolores hic. Beatae voluptatem doloremque aliquam quod. Praesentium quisquam impedit sit omnis explicabo laborum voluptate. Architecto aut est error ea suscipit cum ea. Corporis labore minima qui saepe voluptatibus qui quo. Minus quidem accusantium quis. Ut distinctio id aliquid dolorem facilis dolor. Voluptatem qui non earum voluptas est officia magnam. Possimus eligendi suscipit eius ratione porro sit dolorem. Et voluptates voluptatem aut reiciendis quod. Voluptas eius voluptatibus dolor tempore omnis atque voluptate. Vel esse voluptas alias aut sed deleniti. Ut nesciunt iste quia velit velit est totam. Ea ullam provident dolor rerum. Officia qui dicta illum illum impedit esse. Nemo perferendis nesciunt magnam quasi nostrum repellendus. Est modi et dolor et corporis expedita necessitatibus. Ut id cupiditate nisi sed laudantium dicta culpa. Mollitia ratione magni atque sint. Laboriosam sunt cupiditate officiis est enim tempora. Sit debitis tenetur neque velit officia ab libero. Praesentium at eveniet nesciunt minima nisi iste possimus. Et sequi repellat est natus ullam quis et. Animi omnis qui ut laudantium sit ea fuga. Est tenetur excepturi enim ipsa sint ipsam. Sint aut perspiciatis et aut. Consequuntur magni iusto sed nam eaque praesentium. Cum autem totam minus totam dicta. Adipisci aut esse maxime soluta. Blanditiis exercitationem cumque fugit magnam id. Repellat et optio explicabo provident consectetur doloremque sequi. Sed provident vitae molestiae sunt laudantium amet. Sit nam non animi nobis. Tenetur ipsam ut expedita iure. Aut ducimus ratione et velit.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(8,'aut quo dolorum optio quisquam architecto','1654083931.png','nihil-consequuntur-molestiae','Omnis et accusamus perspiciatis cumque fuga dolor. Maxime quas consequatur nostrum. Ut dolor itaque repellat. Eligendi consequuntur est et libero aut. Laboriosam inventore aut ab quibusdam a. Officiis qui et facere voluptatibus. Et atque asperiores dolor ullam optio expedita. Asperiores dolorem possimus dolorem minus ut. Quaerat autem ex reiciendis ut excepturi accusamus tempora. Consectetur deleniti hic porro reprehenderit incidunt dolorem eius delectus. Asperiores dolore nisi assumenda nisi et quis ut. Est consequatur ut nisi quia et nihil. Quia voluptatem aut iste facere. Eaque officiis ullam ea doloremque aspernatur qui. Earum architecto voluptatem earum eveniet. Tempore quam dolor eveniet quia nihil eos. Quia laborum quas veniam. Odit molestias fugit sed accusamus quam neque. Autem blanditiis perferendis corporis repudiandae consectetur rerum. Ipsum eum est rerum aliquam officiis dicta. Non et quis sed delectus facere deleniti tenetur. Quam nobis et omnis officia temporibus ea. Dolore voluptates quas laboriosam exercitationem. Commodi aliquam ullam delectus ea praesentium. Molestias laboriosam natus debitis est numquam debitis exercitationem. Pariatur fugit repellat perspiciatis ea. Eveniet quia sint modi corrupti aut officia sint nisi. Qui et magni aut sunt. Doloribus optio occaecati ut. Enim quibusdam maiores eos. Error rerum autem totam dignissimos debitis tempore. Quibusdam et nam et fugiat. Unde ducimus in corrupti nemo est consequuntur magni nisi. Sed nihil vitae odit nostrum rerum non eos. Dicta omnis corrupti autem tenetur omnis. Et magnam consectetur quia repellat dolores. Molestiae ad et aperiam repellendus inventore qui et. Labore neque nihil culpa est blanditiis perspiciatis eaque. Saepe mollitia voluptas qui quibusdam magnam unde quasi. Qui aperiam omnis qui tenetur.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(9,'illum iusto enim qui autem ipsum','1654083931.png','eius-ea-voluptatibus','Dolores voluptatem porro labore laudantium illum. Quaerat illum accusantium rerum consequuntur vero consequatur. Aut facilis est doloremque rem molestiae dicta. Qui quae quidem enim eaque sequi et optio corporis. Fuga quaerat facere aut dolorem ut. Id in dicta recusandae consequatur voluptatibus iure mollitia. Quis et sint nulla voluptatem enim vitae. Libero quaerat fugiat odit alias ab deserunt expedita quae. Molestiae maiores veritatis esse consectetur enim. Cupiditate repudiandae tempora aut alias exercitationem quod recusandae. Iusto animi quos alias minima accusantium doloribus. Quidem ratione id veniam assumenda expedita quos. Explicabo perferendis dolorem expedita ad asperiores rerum blanditiis iusto. Ipsam in fuga et. Et aut itaque omnis. Qui porro cumque nulla asperiores quaerat. Ut fugit expedita voluptatem vitae quaerat explicabo. Est et ut eos quia qui labore est. Voluptatem harum tenetur quo voluptatem nostrum. Repudiandae et dolorum natus maiores deserunt. Est voluptate nam ab enim officia accusantium voluptas. Eveniet voluptate doloribus voluptatibus possimus maiores rerum minus voluptates. Excepturi necessitatibus fugiat quidem possimus mollitia culpa. Eius dolorem omnis cumque voluptatibus ut. Similique ex consequuntur cupiditate. Neque laboriosam praesentium hic eligendi veniam natus quidem. Tenetur voluptas eum unde vel quos et. Perspiciatis itaque mollitia nobis. Et numquam assumenda placeat quaerat. Consequatur amet beatae porro praesentium. Earum harum voluptatum et. Sunt enim est dolorem illo necessitatibus. Doloremque non et neque optio consectetur eaque qui. Delectus dolores laboriosam qui. Suscipit beatae nemo et possimus pariatur. Minus quibusdam optio architecto est laboriosam unde quasi laboriosam. Delectus accusamus blanditiis ea blanditiis. Tempore sunt rerum velit amet nam. Sit minima voluptas et accusamus quo. Ut deleniti veniam vel mollitia dolor porro aperiam.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(10,'deleniti est in illum aliquid sit','1654083931.png','consequatur-non-est','Voluptatibus cumque est velit qui nisi aut. Cumque consectetur dolores quos iste. Harum quia nesciunt soluta rerum nostrum ut. Ut voluptatem accusantium eligendi rerum officiis distinctio qui. Et qui impedit assumenda vel qui dolorem. Omnis voluptas facere accusamus nemo omnis. Ad dolorum est quam dolore aliquam recusandae. Labore saepe voluptatem hic aut vel aut doloremque. Odit at nisi enim dolorum tempore. Soluta deleniti natus quia labore. Consectetur officia odio velit quasi est. Iure et vel consequatur aut enim qui eveniet reiciendis. Dicta quidem aut dolore magnam veniam qui. Itaque qui ipsum quia id illo. Sed rerum ea sit vel. Incidunt quos enim voluptate. Rem quia laudantium voluptatibus alias earum. Qui dolore vitae magni. Excepturi eum et facilis consequatur. Velit qui veritatis minus totam. Aut porro quis voluptate a. Quasi mollitia sequi consequatur neque. Vero nam consectetur reiciendis aut similique delectus. Enim quisquam porro qui dolorum quis aut enim. Repellendus quibusdam error qui numquam nesciunt et. Molestiae molestiae expedita unde. Est excepturi maxime et et nihil. Laborum magnam rem consequatur rerum repudiandae quas. Aspernatur enim laboriosam numquam. Iste ut omnis nisi natus iusto et. Voluptatibus aut harum velit officia. In in possimus odio rerum deserunt aut. Molestias nihil nesciunt dicta eius totam sequi aut. Quidem fuga enim libero neque vel. Aliquam dolores eaque quo. Adipisci sint dolore sed sed tempora cupiditate fuga. Et asperiores harum natus fuga. Qui eos beatae ut iste quae sint recusandae et. Quia numquam reprehenderit iusto ullam rerum natus sed. Dignissimos possimus voluptatum beatae consectetur adipisci asperiores.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL);

/*Table structure for table `migrations` */

DROP TABLE IF EXISTS `migrations`;

CREATE TABLE `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=64 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `migrations` */

insert  into `migrations`(`id`,`migration`,`batch`) values 
(55,'2014_10_12_000000_create_users_table',1),
(56,'2014_10_12_100000_create_password_resets_table',1),
(57,'2019_08_19_000000_create_failed_jobs_table',1),
(58,'2019_12_14_000001_create_personal_access_tokens_table',1),
(59,'2022_05_19_104044_create_contactus_table',1),
(60,'2022_05_19_104059_create_pages_table',1),
(61,'2022_05_19_104114_create_settings_table',1),
(62,'2022_05_26_010737_create_products_table',1),
(63,'2022_05_26_011047_create_gallery_table',1);

/*Table structure for table `pages` */

DROP TABLE IF EXISTS `pages`;

CREATE TABLE `pages` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sub_title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `pages` */

insert  into `pages`(`id`,`title`,`image`,`slug`,`sub_title`,`description`,`type`,`created_at`,`updated_at`) values 
(1,'About Us','1654084203.png','about-us',NULL,'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptu','page','2022-06-01 11:32:48','2022-06-01 11:50:03'),
(2,'Fruit And',NULL,'header','Vegetables','Now started','section','2022-06-01 11:32:48','2022-06-01 11:32:48'),
(3,'Terms And Condition',NULL,'terms-and-condition',NULL,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sit amet imperdiet justo, nec tempus lorem. Integer urna sapien, vulputate ac maximus eget, mollis id neque. Ut eu convallis arcu. Donec risus tortor, bibendum a lectus at, egestas posuere mi. In vel auctor risus, ut consequat orci. Nullam aliquet turpis eget suscipit tempor. Ut at orci nunc. Donec eu ante dapibus, scelerisque ligula vel, accumsan magna. Duis dignissim volutpat ex at gravida. Duis fermentum enim est, eu tempus turpis dapibus id. Aliquam condimentum sodales nisi tempus tempus. Vivamus fringilla ligula felis, ut efficitur neque facilisis congue. Cras pellentesque volutpat auctor. Quisque velit lacus, suscipit sit amet erat eu, lacinia blandit nunc. Aliquam ut eros iaculis, pellentesque tortor et, viverra nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In augue massa, rutrum elementum lorem sed, tempus maximus lectus. Aenean tincidunt aliquam nibh blandit dapibus. Quisque fermentum enim blandit ante elementum fermentum. Nulla in malesuada nisl. Morbi ut auctor nisi, vitae congue purus. Phasellus eleifend, purus eget volutpat aliquam, ipsum enim porttitor ante, et vestibulum nibh sem ut nunc. In fermentum turpis orci, a ultricies dui ullamcorper nec. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean dictum mauris at luctus suscipit. Aenean ullamcorper orci in enim sagittis, et maximus quam venenatis. Proin bibendum dolor diam, vitae faucibus nunc pulvinar at. Mauris nunc erat, fringilla vitae nulla nec, lacinia vestibulum sem. Nulla nec nisl at risus aliquam venenatis eu lacinia lacus. Ut auctor nisi sit amet orci interdum, a finibus dolor fringilla. Maecenas sed lacus nisl. Ut blandit lorem urna, vel scelerisque tortor faucibus eget. Etiam nisi metus, placerat vel enim a, maximus semper libero.','page','2022-06-01 11:32:48','2022-06-01 11:32:48'),
(4,'Privacy Policy',NULL,'privacy-policy',NULL,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sit amet imperdiet justo, nec tempus lorem. Integer urna sapien, vulputate ac maximus eget, mollis id neque. Ut eu convallis arcu. Donec risus tortor, bibendum a lectus at, egestas posuere mi. In vel auctor risus, ut consequat orci. Nullam aliquet turpis eget suscipit tempor. Ut at orci nunc. Donec eu ante dapibus, scelerisque ligula vel, accumsan magna. Duis dignissim volutpat ex at gravida. Duis fermentum enim est, eu tempus turpis dapibus id. Aliquam condimentum sodales nisi tempus tempus. Vivamus fringilla ligula felis, ut efficitur neque facilisis congue. Cras pellentesque volutpat auctor. Quisque velit lacus, suscipit sit amet erat eu, lacinia blandit nunc. Aliquam ut eros iaculis, pellentesque tortor et, viverra nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In augue massa, rutrum elementum lorem sed, tempus maximus lectus. Aenean tincidunt aliquam nibh blandit dapibus. Quisque fermentum enim blandit ante elementum fermentum. Nulla in malesuada nisl. Morbi ut auctor nisi, vitae congue purus. Phasellus eleifend, purus eget volutpat aliquam, ipsum enim porttitor ante, et vestibulum nibh sem ut nunc. In fermentum turpis orci, a ultricies dui ullamcorper nec. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean dictum mauris at luctus suscipit. Aenean ullamcorper orci in enim sagittis, et maximus quam venenatis. Proin bibendum dolor diam, vitae faucibus nunc pulvinar at. Mauris nunc erat, fringilla vitae nulla nec, lacinia vestibulum sem. Nulla nec nisl at risus aliquam venenatis eu lacinia lacus. Ut auctor nisi sit amet orci interdum, a finibus dolor fringilla. Maecenas sed lacus nisl. Ut blandit lorem urna, vel scelerisque tortor faucibus eget. Etiam nisi metus, placerat vel enim a, maximus semper libero.','page','2022-06-01 11:32:48','2022-06-01 11:32:48');

/*Table structure for table `password_resets` */

DROP TABLE IF EXISTS `password_resets`;

CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `password_resets` */

/*Table structure for table `personal_access_tokens` */

DROP TABLE IF EXISTS `personal_access_tokens`;

CREATE TABLE `personal_access_tokens` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `personal_access_tokens` */

/*Table structure for table `products` */

DROP TABLE IF EXISTS `products`;

CREATE TABLE `products` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sub_title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `products` */

insert  into `products`(`id`,`title`,`sub_title`,`slug`,`image`,`description`,`created_at`,`updated_at`,`deleted_at`) values 
(1,'porro doloremque voluptatem facilis recusandae repellat','aut atque tempora quam nihil autem','possimus-mollitia-harum','1654083984.png','In accusantium dolor quaerat ducimus. Commodi enim dolorem consequatur consequatur inventore. Veniam saepe exercitationem quo aut occaecati harum. Quaerat ratione dolor voluptas et laboriosam voluptatum porro aut. Sapiente beatae possimus est deserunt non architecto reprehenderit. Fugit tenetur accusamus explicabo quia ullam. Eum ut id debitis quidem. Ipsa ducimus dolor quasi quia. Consequuntur vero corporis possimus nihil dolore. Dolorem quia neque labore est placeat. Voluptatem et atque ut dolore quia. Facere autem accusamus molestias facilis repellendus ipsum nemo. A explicabo vel labore officia suscipit. Omnis provident aliquam qui facilis. Quis voluptatum ut eaque magni perferendis. Tempore esse reprehenderit soluta tenetur minus doloribus voluptatum. Provident repellat aspernatur ipsum qui odio vel voluptatem nesciunt. Velit minima quia tenetur temporibus delectus. Est minus cumque adipisci nobis dolores velit. Ab id necessitatibus voluptate et. Quidem reiciendis deserunt et expedita tempore impedit voluptas. Non ut eaque quam iure optio eveniet est. Distinctio nam quidem iusto dolorem ut dignissimos. Velit corporis cumque tenetur asperiores. Eum recusandae accusantium deleniti recusandae. Sunt provident vitae doloribus impedit libero. In impedit et pariatur labore fuga vel ullam. Delectus et necessitatibus at. Sint et dolores a et est et corrupti voluptas. Rem qui doloremque delectus sit corporis incidunt. Ratione rerum quis qui doloribus cumque dolorum facere. Et nisi quo dolor est nam. Expedita consequatur nisi quasi accusamus fugiat. Est doloribus aut excepturi cumque necessitatibus doloremque. Porro cumque accusantium omnis voluptate. Minus quas iusto totam non. Tempora facere quia voluptatem iure qui et illum ratione. Sit sint similique omnis ipsam qui repudiandae. Temporibus commodi minima tempore dolore. Perferendis cupiditate eius provident qui asperiores vel velit.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(2,'voluptatem maxime voluptates odio voluptates omnis','est sed nihil aut nesciunt minima','suscipit-facilis-maxime','1654083984.png','Earum enim voluptas sit voluptas. Dolorem ratione aut sed et. Dicta facere consequatur nam dolor odit facilis autem. Ea quia dolorem eum fuga repellat voluptate. Et ex ipsum ducimus illum accusamus animi expedita alias. Asperiores minima ullam officiis sed eius. Voluptas esse ipsa totam laboriosam. Fugiat consequuntur praesentium id odio. Vero accusamus quis eum quibusdam magni. Autem quod eos dolorem tempora iste quisquam iste reiciendis. A dicta adipisci reprehenderit qui soluta quidem rerum necessitatibus. Tempore sit sint itaque laudantium quos vel. Cumque qui molestiae quos iste blanditiis maxime. Dignissimos accusantium et dignissimos consequatur commodi est quia. Et incidunt repellendus excepturi nesciunt dolorem non in qui. Sed dignissimos mollitia consequuntur voluptas aspernatur in sit deleniti. Et voluptas eligendi vero eum. Consequatur illum quis pariatur in rerum aut. Vel recusandae eos mollitia officia et quos modi sit. Voluptatem nesciunt totam error qui. Rerum explicabo quas rerum ea aliquid. Sed eum quidem necessitatibus nemo consequuntur quaerat molestiae. Numquam delectus ipsa molestiae quia suscipit. Voluptatem exercitationem et est architecto officia doloremque dicta. Vel dicta voluptate ad voluptatibus quidem aut est. Vel omnis ut eligendi ut ut delectus ut odio. Et iure est et et. Voluptate deleniti praesentium et. Ut quia qui totam ea iste dicta. Sapiente excepturi aut numquam delectus voluptatibus hic. Ratione consequatur eos eligendi et voluptatem. Est voluptatem iste eum unde. Consequatur cumque animi labore. Dolorem vitae dolore adipisci maiores maiores perferendis voluptate. Alias laboriosam fugiat laboriosam quia labore. Tempora adipisci temporibus quibusdam aspernatur doloribus qui sint. Rem earum et et nobis. Ad laboriosam in cupiditate numquam modi. Velit expedita ut a qui illo et veritatis. Velit asperiores qui nemo laborum ex.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(3,'et omnis repellendus non et voluptatem','autem voluptas sed recusandae aperiam minima','a-nihil-ipsa','1654083984.png','Consectetur culpa doloremque est maxime quis autem ex fugiat. Saepe suscipit dolor ad ad. Ex distinctio et quaerat quod. Est necessitatibus amet id qui ducimus. Nulla qui ut est modi aliquid minima dolorum doloribus. Maxime illum libero sunt debitis quo sed ex. Rem molestiae quisquam saepe maxime. Impedit ad rerum ut autem quia. Et explicabo ex reiciendis est placeat aut iure voluptatibus. Est placeat qui quidem saepe accusantium vel soluta. Ut nam provident ab ipsa aut ea perspiciatis officia. Optio eaque vero recusandae est possimus aperiam. Et vero ea explicabo iusto voluptate modi quia. Vel non explicabo et eos ex perferendis in. Cumque quos ipsa autem voluptatum. Ex nesciunt voluptatibus aliquid sint natus odit omnis. Architecto dolores aut architecto impedit. Voluptatem aut inventore facilis aspernatur voluptate corporis. Voluptatem qui sint voluptas. Quis id sint rem occaecati non tenetur. Aut ipsa dolorum odio molestiae. Assumenda sit quas consequatur natus pariatur temporibus vel labore. Eaque itaque maiores enim ullam eveniet. Provident voluptas qui cum rem amet incidunt. Voluptatem et accusamus aperiam odit et explicabo occaecati. Aut est ratione est eos velit sit. Distinctio nihil qui tempora ipsum. Autem et culpa voluptate aliquam tempore. Eos rerum expedita explicabo sequi rerum in ut aut. Magni odio voluptate iusto accusamus in et rem facilis. Voluptates unde praesentium sint quidem. Neque quo sit sed molestiae. Aliquam in delectus quis libero repellat rerum corporis. Quos quisquam autem odit dolore nisi temporibus. Aut voluptatem voluptatibus facilis amet suscipit et fugit. Culpa ea voluptatem consectetur molestiae unde. Unde mollitia neque quia rerum. Cumque hic expedita illum nesciunt illo iusto. Praesentium esse adipisci totam sed adipisci. Vel assumenda quia veritatis repudiandae.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(4,'temporibus ratione a dolorum dignissimos incidunt','et aut nostrum architecto qui harum','vel-et-repellendus','1654083984.png','Qui qui ut totam deleniti vitae alias. Nesciunt saepe aut impedit. Voluptatem qui omnis voluptatem eligendi repellat. Molestias quibusdam consequatur quis dolores voluptatibus quia accusantium. Sunt quasi quae eligendi provident perferendis magnam aut. Voluptate excepturi quasi quia deleniti dolor a eos velit. Occaecati non ipsam velit harum. Soluta nihil labore maxime earum voluptas. Voluptatem quidem numquam in ut consequatur expedita. Et magnam consequatur accusantium. Praesentium veritatis esse deserunt accusamus blanditiis perferendis. Culpa enim laboriosam earum. Voluptatem quo libero voluptatem occaecati cumque. Fuga in dolorem est ex pariatur vel. Culpa suscipit sit assumenda exercitationem magnam. Magnam ipsum sunt assumenda dignissimos. Nemo voluptas dolor fugit mollitia optio non sit. Fugit blanditiis exercitationem voluptas et repellat aut in sunt. Vitae est cum natus eum et non. Animi eveniet voluptatum quisquam facilis. Eligendi iure tempora numquam labore. Facere aliquid ut vel modi consectetur laborum. Laborum repellat occaecati eius non asperiores qui. Vitae non officiis sit rerum et dolorem nihil. Et soluta aperiam quisquam quod qui quis et velit. Libero distinctio dolorum aliquam perspiciatis alias. Qui non dolor veniam numquam ab. Quia placeat consequatur itaque officia dolorem. Facere reprehenderit non beatae provident dolorem similique. Voluptate veniam autem consequatur. Illum delectus et ut necessitatibus itaque sit libero. Maxime dolores iste sequi ex est molestiae. Animi veritatis tempora odio blanditiis. Quisquam quis dolorem quia eos. Dolores animi necessitatibus eius. Culpa repellat aut aut eum nihil ratione. Dolore libero illum doloremque corrupti voluptas. Rerum corrupti rerum placeat omnis repudiandae molestias. Aliquam aperiam sit non et repellendus quae. Sapiente eum possimus ullam eveniet ratione.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(5,'provident sint quaerat officia ratione et','autem facilis impedit occaecati doloribus est','libero-natus-ut','1654083984.png','Officia qui adipisci amet ad. Est natus eius vero delectus possimus. Et totam qui harum illo enim saepe. Tempora voluptatem accusantium consequatur aspernatur sunt sit. Deserunt tenetur harum maiores. Ut voluptatum aut nihil. Soluta et praesentium sunt consequatur doloribus voluptas. Reiciendis quia non rerum ut ex. Quasi sint sequi quod nemo officiis nihil et. Ad deserunt sequi modi a iusto. Ad aut voluptatum rerum. Molestias fugiat quisquam ab corporis id tempore. Distinctio ut illo ea aut pariatur voluptates deleniti. Inventore delectus atque voluptates aut delectus molestiae est tempora. Et iusto quae esse inventore ullam. Distinctio sunt dolor vero sapiente nihil quam provident voluptatem. Quo voluptates blanditiis est et velit odio. Et voluptatum sequi et reiciendis ea quas. Perferendis omnis quasi suscipit sed. Minus nam ipsa aut sed similique molestiae sunt. Cupiditate cupiditate eius labore molestiae dolore consequatur quia. At quasi delectus tenetur sint a eum. Est voluptas dolorem voluptas tenetur. Nihil quam ullam quas laboriosam vel. Consequatur earum natus ex quibusdam est. Temporibus aut et recusandae autem. Autem odit nostrum quasi et numquam ab. Quam ut quis commodi quisquam distinctio. Eos id exercitationem assumenda et ducimus. Enim reprehenderit culpa corrupti unde cumque est quam fugiat. Dolores velit voluptatem voluptates praesentium totam voluptatem. Placeat omnis enim exercitationem fugiat veritatis. Accusantium inventore ex cumque dolor. Nihil ut vel excepturi nihil fugit id eveniet. Velit nobis sit beatae deleniti expedita et aliquid reprehenderit. Veritatis et similique consequuntur eos. Tempora consectetur quis velit hic. Modi sed et rerum quo iure. Vero accusamus ut blanditiis eum eos quod. Natus accusantium accusamus qui alias.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(6,'et voluptatum officia accusantium dolorem ut','temporibus tempore quis vero distinctio quis','exercitationem-et-error','1654083984.png','Dolor eos et iste quis nobis tempore. Eligendi et praesentium voluptatum veniam. Quisquam nemo non praesentium deleniti quae. Quaerat dolor officia dicta aliquam sed. Fugiat sed molestiae voluptatum expedita velit et. Libero incidunt quaerat maxime quae. Temporibus delectus et et natus pariatur. Nisi dolores veniam velit voluptatem aperiam fugit. Similique iure dolorem accusamus rerum. In tempora fugiat aut dolor numquam quo necessitatibus voluptatibus. Ipsum quis beatae nisi repellendus sed modi. Veniam in quo illum. Fugiat dolor distinctio doloribus voluptas laborum. Inventore eum odio minima in. Dolorem qui labore omnis omnis fuga non. Consectetur excepturi quae quasi voluptatem. Aut beatae dolore ut recusandae error accusamus. Modi suscipit nulla provident qui officiis reiciendis pariatur. Est fugiat temporibus soluta debitis et omnis. Qui id assumenda nihil ratione. Adipisci corporis eum fuga non consectetur ea ad. In qui quia vel iure laudantium. Expedita vel nesciunt est minima est vitae nihil. Aut a nulla ex necessitatibus explicabo ratione harum. Molestiae beatae sint eum veritatis. Voluptas porro voluptatem autem ex cumque. Natus illo et perferendis delectus hic. Dolor dicta praesentium sapiente fugit. Corrupti sint ipsum sed quasi dolores. Consequatur eos et sapiente mollitia provident quis repudiandae consequuntur. Quo possimus consequatur minus quia natus eveniet aut. Perspiciatis reiciendis dolorem aut cupiditate aperiam. Inventore omnis debitis a vitae voluptatem reprehenderit. Aspernatur dolor illo sequi doloremque. Ratione aut ipsum tempore ipsam sit. Ut at ut incidunt sit non repudiandae ducimus ipsum. Repellat sunt sunt non deserunt atque at enim consectetur. Minima tempore molestias exercitationem illum consequatur ea. Nihil rerum accusantium et ut. Voluptatem qui nihil illo aut.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(7,'quae animi expedita modi cupiditate perferendis','deserunt et ipsum et sunt vero','consequatur-et-minus','1654083984.png','Veritatis est laboriosam magni perspiciatis quaerat. Dolor tempore aperiam quis officiis. Quo eveniet necessitatibus voluptatem voluptatem libero itaque doloremque. Et laboriosam aut in odit cumque quam numquam. Enim reprehenderit asperiores vero eaque quidem fugit eos. Quo exercitationem velit ad consequuntur repudiandae ut. Quia sequi ullam a dicta sit sed. Non reprehenderit et voluptatum ea omnis. Laborum fuga nam neque ea consequatur. Sit architecto omnis odio ab necessitatibus non. Laboriosam omnis sit necessitatibus expedita a quis. Qui libero ut molestias aut voluptas impedit rerum. Nihil alias veniam veniam suscipit dignissimos. Repudiandae aliquid quidem dolores odit cumque dolorum. Id enim ad qui quia ea. Suscipit et eos possimus saepe molestiae ut rerum. Officiis possimus doloribus dolores qui dolore dolorum animi. Quis atque nihil nobis dolore non. Sed ut odit illo quia voluptatem. Sit natus ut nihil doloremque consequatur libero et. Alias eligendi numquam aut quidem vero dolorem officiis. Corporis consequatur beatae itaque. Ullam voluptatem quia quod. Neque qui suscipit excepturi deserunt voluptas. Et aut et aliquam. Est eum voluptates autem dignissimos. Sed dolorum non occaecati incidunt qui ullam. Qui odit quia delectus et nihil. Quaerat libero quia amet nihil animi et iste similique. Adipisci neque fugiat expedita omnis. Voluptas vel sit ea laudantium voluptatibus magni. Soluta dolorem nihil ex aliquam est porro incidunt. Aut magnam laudantium assumenda quo aut. Deserunt dolore voluptas est dolore. Veniam sed sint facere. Et earum aut deleniti accusamus placeat debitis. Omnis et officia dolor reprehenderit distinctio. Debitis modi porro cum fugit quaerat ea. Voluptas doloribus et dolorem. Qui et dolor delectus cupiditate perspiciatis quia.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(8,'adipisci atque eos ut quo est','quo quibusdam ratione iusto quisquam saepe','quae-ad-ea','1654083984.png','Ratione autem voluptas aut quisquam molestiae quia qui debitis. Quis inventore et eius blanditiis porro consequatur. Voluptatem eveniet eveniet eos et dicta. Sequi provident consequuntur ab est omnis maiores impedit. Aut dolores qui similique possimus sed et consectetur. Autem quas et ut. Commodi illum error quia. Libero necessitatibus numquam voluptas similique cum modi quisquam. Quod voluptatibus quae amet temporibus error consequatur. Sunt sit dicta distinctio provident voluptates. Nemo est qui quidem aut. Est itaque explicabo repudiandae dolorum. Consequuntur recusandae reprehenderit pariatur maiores architecto deserunt iste. Et ipsum sed ut et et pariatur. Porro odio velit aut. Numquam aperiam itaque ad sit. Id in laudantium possimus nihil ad dicta possimus. Aut placeat laborum est natus non id doloribus. Totam distinctio mollitia voluptatem repellendus. Explicabo nihil voluptas dolorum eum repellendus cum consequatur. Ut fugit repudiandae tempore. Deserunt cum aliquam unde tempora enim quisquam laboriosam. Quia tenetur et quod magni dolorum quo molestias. Et quidem natus autem dolorem vel libero. Repellendus ipsa consequuntur sed veniam explicabo sint voluptatibus. Expedita impedit quia suscipit fugit voluptatem. Sed hic et quo rerum quia. In laboriosam fugiat quo repudiandae voluptas. Illum consequatur at delectus inventore. Harum sit amet et dolorum. Numquam dolor maiores sint dolor ad. Numquam culpa et aliquam nisi. Facilis cumque itaque odit maiores dicta illum et. Ratione et consequuntur nulla quaerat. Eius tenetur ab sit et. Voluptatem rerum ad beatae sed ea nihil. Facere hic in itaque quia blanditiis architecto minima. Rerum velit eligendi qui quaerat sit molestias. Et quibusdam eos possimus rerum aut sequi eum. Officia et maxime et totam autem debitis.','2022-06-01 11:32:48','2022-06-01 11:46:24',NULL),
(9,'consectetur recusandae optio sunt debitis voluptate','molestiae ut perspiciatis dolores molestiae quia','voluptatem-odit-tempora','1654083984.png','Nostrum praesentium ipsum est sapiente nisi. Quo eius laudantium ut nisi eum. Iusto est delectus sunt magnam fugiat et. Molestiae ut tenetur laborum molestias omnis enim. Illo et consectetur eveniet officiis rem. Rem in voluptates velit tempora sed qui accusamus ducimus. Quaerat veniam dicta fugit fuga animi. Voluptatem est praesentium itaque officiis voluptatibus. Voluptas illum in nesciunt. Voluptas libero ut rerum magni in et. Culpa quod labore dignissimos. Quia voluptatem ut praesentium molestiae nulla officiis. Voluptatem laudantium omnis possimus accusantium rerum maxime accusantium. Sint eum placeat nesciunt aut vitae beatae suscipit. Blanditiis similique et natus nesciunt voluptate. Est corrupti dolore et est dolores ut magnam inventore. Rerum repellendus qui et sit asperiores ad. Sed eligendi ad fugiat officiis. Nobis temporibus ab cupiditate asperiores debitis autem nihil. Quod qui fugiat et et cum recusandae unde. Dolorem optio eos recusandae cupiditate. Aperiam quae consequatur et vero vel et. Ab ab numquam nisi illum nobis consequatur non. Soluta natus hic accusamus quia. Et natus dolorem officiis eaque delectus aut. Ut officia voluptatum sunt dicta quia tempore ut. Soluta consequuntur velit nam nostrum inventore quis est. Repellendus quas et autem est quaerat quos commodi et. Ut totam officiis vero nostrum. Officia ut repellat et ratione nulla voluptatum ab saepe. Ullam beatae soluta eveniet repellat molestiae qui. Asperiores ut voluptatem omnis ducimus ullam dignissimos cum. Et ipsa aut provident iste praesentium enim. Et accusamus ullam ipsa. Ex maxime consequatur hic optio dolorem. Ea odit facilis neque qui. Deserunt est ut ut. Consequatur est ut provident. Perferendis nobis voluptatem deserunt iusto nihil assumenda. Molestiae et quo et modi incidunt.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL),
(10,'aliquam ut ut porro accusantium eum','et consectetur aliquam qui rem officiis','nisi-qui-distinctio','1654083984.png','Nulla qui qui dolor temporibus. Vel consectetur beatae nihil architecto. Et sed itaque voluptatibus expedita. In quia sed sit tempore voluptas impedit eum. Et quia perspiciatis veniam explicabo deserunt. Eum possimus iusto sit deleniti quo sed. Provident pariatur enim eveniet. Eos quo doloribus et suscipit nihil minus recusandae. Cupiditate a culpa quae excepturi in autem. Necessitatibus quia et quis aut. Illum quis quis corporis fugiat. Quo assumenda neque sint odit consequatur ut. Omnis libero suscipit aliquid ratione. Quam pariatur fugit quae sint et temporibus. Sequi ipsam quia molestias ipsa corporis. Aut earum cum atque illum rerum. Aut porro magni labore impedit provident. Ut velit ipsum sint nesciunt voluptas. Eveniet facilis a facere quia illo minima. Architecto quia et sed fugit dolor. Ea architecto facilis error et officiis exercitationem incidunt. Repellat impedit dolorem exercitationem rerum ab. Dolore accusamus ut consequatur molestias fugiat. Omnis eius aut reiciendis qui. Quod et unde voluptatem ullam delectus. Sit sunt assumenda quae necessitatibus voluptatibus placeat aut impedit. Exercitationem dolorum aut ea harum vero eum qui cum. Deserunt impedit magni quas quod et ex. Reprehenderit vel tempore est in sunt cupiditate nisi. Vel necessitatibus est et sit. Incidunt ex culpa omnis repellendus. Aut ab odio iusto amet. Hic dolorem sit ut voluptates quaerat. In possimus porro soluta expedita non. Vel animi perferendis iure rerum. Deserunt molestias voluptatem iste optio ut non exercitationem. Nihil nisi sapiente quisquam qui cum. Libero consequuntur quos aut eum ab. Labore nam quos aliquid asperiores maiores. Minus rerum saepe delectus.','2022-06-01 11:32:48','2022-06-01 11:32:48',NULL);

/*Table structure for table `settings` */

DROP TABLE IF EXISTS `settings`;

CREATE TABLE `settings` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `class` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `link` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `settings` */

insert  into `settings`(`id`,`title`,`class`,`link`,`created_at`,`updated_at`) values 
(1,'facebook','fa fa-facebook','http://facebook.com','2022-06-01 11:32:49','2022-06-01 11:32:49'),
(2,'twitter','fa fa-twitter','http://twitter.com','2022-06-01 11:32:49','2022-06-01 11:32:49'),
(3,'demo@gmail.com','fa fa-envelope','http://gmail.com','2022-06-01 11:32:49','2022-06-01 11:32:49');

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `users` */

insert  into `users`(`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`) values 
(1,'Mrs. Kailee Walter','lkuhlman@example.org','2022-06-01 11:32:47','$2y$10$uHigytUsKp0DmklH.pZbYerY1FSNKlZTaWiUczobwVDnjW7Z6vaM.','G1cdoibpHY','2022-06-01 11:32:48','2022-06-01 11:32:48'),
(2,'Mrs. Tomasa Kozey II','nadams@example.net','2022-06-01 11:32:47','$2y$10$W94june.pZTlnLMX/qHQou72cyXzb0TMU0f4AzEgU9DH9oUmARcMW','JbAUwksBb9','2022-06-01 11:32:48','2022-06-01 11:32:48'),
(3,'Mikayla Tillman IV','ostamm@example.net','2022-06-01 11:32:47','$2y$10$SVy7uDdzYl40MV9jkFptCugudCUxUvvYsPQZmS8yjkRO3wiHm/fIS','LAC7yNCO9L','2022-06-01 11:32:48','2022-06-01 11:32:48'),
(4,'Ralph Nikolaus','zdavis@example.com','2022-06-01 11:32:48','$2y$10$o0aJZIqV.Qp3fgSyZwB0V.9JKSauobz7GGcz2gb.L9Zfe8WVPzway','oh9tm9gnQb','2022-06-01 11:32:48','2022-06-01 11:32:48'),
(5,'Jana Ullrich','jamison69@example.org','2022-06-01 11:32:48','$2y$10$4F2cIAaQu/1KCIuizTGhEO/29Z8tKzHUjeL3a5cocOTSU7R7KTpTu','35rIb5URu5','2022-06-01 11:32:48','2022-06-01 11:32:48'),
(6,'Emile Trantow','haleigh.boehm@example.com','2022-06-01 11:32:48','$2y$10$IU3aKvfsHva5HeDYjYPrfud4X3FJTGOTlYGJLMrjKCwrZls6wcToy','orlxnwsmQb','2022-06-01 11:32:48','2022-06-01 11:32:48'),
(7,'Mr. Ray Goyette','ryan.alyce@example.net','2022-06-01 11:32:48','$2y$10$IVYdulclwc4xChrA2oWDxeohUWLrG1I9lBUlqiAcDamjwn7Fpacr6','bu8nV4LIZe','2022-06-01 11:32:48','2022-06-01 11:32:48'),
(8,'Shany Blick','psporer@example.com','2022-06-01 11:32:48','$2y$10$OnyZt0aVV8YI8m/KoS0aE.flHx5MVht.ZGPAqXOMTt0WpX7ijACey','sZGODoRPS2','2022-06-01 11:32:48','2022-06-01 11:32:48'),
(9,'Kade Dickinson','dolores.kuvalis@example.com','2022-06-01 11:32:48','$2y$10$Q5/MtcuTbhp8fbJf7MYDuOrdxj01fFX2YqqPsDljKvuEngg0zBY5e','Wwmpuq4FLL','2022-06-01 11:32:48','2022-06-01 11:32:48'),
(10,'Mr. Lorenzo Mante','josh42@example.com','2022-06-01 11:32:48','$2y$10$/qtR0sc.x9PPgOYlHcZ8MuV1mDAJKpQ1..GMmc.vGoS2uSW.HcHya','7N4N1mDH7d','2022-06-01 11:32:48','2022-06-01 11:32:48');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
